### PR TITLE
7.x 2.x tests

### PR DESCRIPTION
**Pull request by levelos**
@ruscoe, I believe we want the pull requests to be against 2.x not 1.x. Closing #3. Ref. #1.

### CODE REVIEW

**Comment by levelos** [comment]
@ruscoe, great work on these tests!

I'm getting 2 errors when running them:

```
WD mandrill: Failed sending email from simpletest@example.com to recipient.one. invalid: no message                                                                                              [error]
WD mandrill: Failed sending email from simpletest@example.com to . invalid: no message                                                                                                           [error]
```

Also, we can we add test coverage for all of our hooks as defined in mandrill.api.php? Let me know how much trouble that would be. Note that a common pattern is to have a mandrill_test.module that will implement those hooks. One option at least.

**Comment by ruscoe** [comment]
@levelos This should be good to merge now.

**Comment by levelos** [comment]
@ruscoe, afraid I'm still getting the following error:

```
WD mandrill: Failed sending email from simpletest@example.com to recipient.one. invalid: no message [error]
WD mandrill: Failed sending email from simpletest@example.com to . invalid: no message [error]
```

**Comment by ruscoe** [comment]
@levelos Really strange that I'm not able to get those. I'll try testing some more but might have to check out your local installation.

**Comment by ruscoe** [comment]
@levelos Found it. Had to implement a "test mode" variable in order to test failure without logging errors. It's similar to what I did for the MailChimp tests. Changes in these commits: https://github.com/thinkshout/mandrill/commit/91d81ae34c7b97a0fa7e7c48401c422e9f83c31f https://github.com/thinkshout/mandrill/commit/cdfdb3216e0a5c45301620cc3a803978d1d30194

**Pull request merged**
